config/routes.rb
Rails.application.routes.draw do

devise_for :users
root 'home#index'

resources :challange_walls, except: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challange_wall.rb
class ChallangeWall < ApplicationRecord
	belongs_to :user
	validates :title, presence: true, length: {maximum: 160}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :challange_walls, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/challange_walls_controller.rb
class ChallangeWallsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_challange_wall, only: [:show, :edit, :update, :destroy]


  # GET /challange_walls/1
  # GET /challange_walls/1.json
  def show
  end

  # GET /challange_walls/new
  def new
    @challange_wall = ChallangeWall.new
  end

  # GET /challange_walls/1/edit
  def edit
  end

  # POST /challange_walls
  # POST /challange_walls.json
  def create
    @challange_wall = ChallangeWall.new(challange_wall_params)
    @challange_wall.user = current_user
    respond_to do |format|
      if @challange_wall.save
        format.html { redirect_to @challange_wall, notice: 'Challange wall was successfully created.' }
        format.json { render :show, status: :created, location: @challange_wall }
      else
        format.html { render :new }
        format.json { render json: @challange_wall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challange_walls/1
  # PATCH/PUT /challange_walls/1.json
  def update
    @challange_wall.user = current_user
    respond_to do |format|
      if @challange_wall.update(challange_wall_params)
        format.html { redirect_to @challange_wall, notice: 'Challange wall was successfully updated.' }
        format.json { render :show, status: :ok, location: @challange_wall }
      else
        format.html { render :edit }
        format.json { render json: @challange_wall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challange_walls/1
  # DELETE /challange_walls/1.json
  def destroy
    @challange_wall.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Challange wall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challange_wall
      @challange_wall = ChallangeWall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def challange_wall_params
      params.require(:challange_wall).permit(:title)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@challange_walls = ChallangeWall.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challange_walls_helper.rb
module ChallangeWallsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/challange_walls/_form.html.erb
<center>
  <%= simple_form_for(@challange_wall) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</center>

app/views/challange_walls/edit.html.erb
<center>
<h1>Editing Challange Wall</h1>

<%= render 'form', challange_wall: @challange_wall %>

<%= link_to 'Show', @challange_wall %> |
<%= link_to 'Back', root_path %>

</center>

app/views/challange_walls/new.html.erb
<h1>New Challange Wall</h1>

<%= render 'form', challange_wall: @challange_wall %>

<%= link_to 'Back', root_path %>

app/views/challange_walls/show.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>
<%= link_to 'Edit', edit_challange_wall_path(@challange_wall) %> |
<% end %>
<%= @challange_wall.title %> 
<br>
<%= link_to 'Back', root_path %>

app/views/home/index.html.erb
<center>
<p id="notice"><%= notice %></p>


<h1>Challange Walls - to ma być z tego co rozumiem karuzela z kategoriami</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @challange_walls.each do |challange_wall| %>
      <tr>
        <td><%= link_to challange_wall.title, challange_wall %></td>
          <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_challange_wall_path(challange_wall) %></td>
          <td><%= link_to 'Destroy', challange_wall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'shared/menu' %>
  	<%= render 'shared/banner' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_banner.html.erb
</div>
<div class="banner">
<%= link_to 'To jest miejsce na banner', root_path, class: "navbar-brand" %>
</div>

app/views/shared/_footer.html.erb
<footer> 
	<p> <center>
		copyright by © Natalia Niziolek & Mikolaj Szkurlat
	</center></p> 
</footer>

app/views/shared/_menu.html.erb
<div class="navbar" >
	
	<center>

		<% if user_signed_in? %>
			Hello, <%= current_user.email %>!
			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> |
			<%= link_to "Create a new challange wall", new_challange_wall_path, :class => 'navbar-link' %>
		<% else %>
			<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>	
		<% end %>
	
	</center>